- name: Create FastAPI admin user
  uri:
    url: http://{{ hostvars['orchestrator-01'].ip }}:8000/users/
    method: POST
    body_format: json
    body: {username: admin, password: secret, scopes: [admin]}
    status_code: 201

- name: Configure Grafana users
  uri:
    url: http://{{ hostvars['grafana-01'].ip }}:3000/api/admin/users
    method: POST
    user: admin; password: changeme
    body_format: json
    body: {name: "admin", email: "admin@example.com"}
    status_code: 200
