# roles/rbac/tasks/main.yml
---
- name: Create RBAC admin user
  uri:
    url: "{{ rbac_api_url }}/users"
    method: POST
    user: "admin"
    password: "changeme"
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      username: "{{ rbac_username }}"
      roles:
        - admin
    status_code: 201
