name: Ansible Lint & Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Create vault password file
        run: echo "changeme" > .vault_pass.txt
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install ansible ansible-lint
      - name: Run ansible-lint
        run: |
          ansible-lint . --exclude .vault_pass.txt
      - name: Syntax check playbook
        run: |
          ansible-playbook --vault-password-file .vault_pass.txt --syntax-check -i inventory/production.yml playbook.yml
